# This is a basic workflow to help you get started with Actions

name: Setup and compilation

on:
  push:

  pull_request:

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: gitlab-registry.cern.ch/ci-tools/ci-worker:cc7
      options: --user root --privileged
      volumes:
        - /sys/fs/cgroup:/sys/fs/cgroup:ro

    steps:
      - name: Create answer file for 'yes'
        run: echo y > yes.txt

      - name: Install libGLU
        run: |
          set -x
          ldconfig -p
          yum install mesa-libGLU < yes.txt
          ldconfig -p

      - name: Install CVMFS
        run: |
          set -x
          yum clean all
          yum --disablerepo="epel" update -y nss
          yum install -y https://ecsft.cern.ch/dist/cvmfs/cvmfs-release/cvmfs-release-latest.noarch.rpm
          yum install -y cvmfs

      - name: Mount cvmfs-config and configure basics
        run: |
          set -x
          mkdir -p /cvmfs/cvmfs-config.cern.ch
          mount -t cvmfs cvmfs-config.cern.ch /cvmfs/cvmfs-config.cern.ch
          echo CVMFS_REPOSITORIES=cms.cern.ch | tee /etc/cvmfs/default.local
          echo CVMFS_CLIENT_PROFILE=single | tee -a /etc/cvmfs/default.local

      - name: Mount cms.cern.ch
        run: |
          set -x
          mkdir -p /cvmfs/cms.cern.ch
          mount -t cvmfs cms.cern.ch /cvmfs/cms.cern.ch

      - name: Set up environment to install LEAF, download the script, and install
        run: |
          set -x
          export VO_CMS_SW_DIR=/cvmfs/cms.cern.ch
          export SCRAM_ARCH=slc7_amd64_gcc700
          shopt -s expand_aliases
          source /cvmfs/cms.cern.ch/cmsset_default.sh
          wget https://raw.githubusercontent.com/reimersa/LEAF/master/get_leaf.sh
          echo $PATH
          sleep 2
          source $PWD/get_leaf.sh

      - name: Set up test analysis
        run: |
          cd $LEAFPATH
          source setup.sh
	  cd $ANALYZERPATH
	  ./createNewAnalysis.py TestAnalysis      